
# server??
server:
  port: 8989
  servlet:
    context-path: /api

# ?????
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/yupi
    username: root
    password: abc123
    driver-class-name: com.mysql.cj.jdbc.Driver
  #session失效时间
  session:
    timeout: 86400
# mybatis-plus???
mybatis-plus:
  type-aliases-package: com.yupi.usercenter.model.domain    #??????
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: false